from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def draw_header(c, title, y):
    c.setFillColor(colors.HexColor("#27374D"))
    c.rect(40, y, 515, 20, fill=True, stroke=False)
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(colors.white)
    c.drawString(45, y + 5, title)
    c.setFillColor(colors.black)

def draw_boxed_section(c, x, y, w, h, title, content_lines):
    c.setStrokeColor(colors.HexColor("#999999"))
    c.rect(x, y - h, w, h, stroke=True, fill=0)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(x + 5, y - 15, title)
    c.setFont("Helvetica", 9)
    for i, line in enumerate(content_lines):
        c.drawString(x + 5, y - 30 - (i * 12), line)

def generate_template_pdf(filename="template_notice.pdf"):
    c = canvas.Canvas(filename, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 14)
    c.drawString(40, height - 40, "CARGO ARRIVAL NOTICE")
    c.setFont("Helvetica", 9)
    c.drawString(40, height - 55, "Generated by {{company_name}}")

    # Reference Header
    draw_header(c, "REFERENCE DETAILS", height - 75)
    c.setFont("Helvetica", 9)
    c.drawString(50, height - 95, "Ref: {{ref}}")
    c.drawString(250, height - 95, "Issuer: {{issuer}}")
    c.drawString(50, height - 110, "Job Ref No: {{job_ref}}")
    c.drawString(250, height - 110, "Invoice Ref: {{invoice_ref}}")
    c.drawString(50, height - 125, "Issued By: {{issued_by}}")
    c.drawString(250, height - 125, "Invoice Date: {{invoice_date}}")

    # Shipment Details
    draw_header(c, "SHIPMENT DETAILS", height - 150)
    c.drawString(50, height - 170, "Origin: {{origin}}")
    c.drawString(250, height - 170, "Destination: {{destination}}")
    c.drawString(50, height - 185, "ETA: {{eta}}")

    # Consignee
    draw_boxed_section(
        c,
        40, height - 200,
        250, 80,
        "CONSIGNEE",
        ["{{consignee_line_1}}", "{{consignee_line_2}}", "{{consignee_line_3}}", "{{consignee_gst}}"]
    )

    # Shipper
    draw_boxed_section(
        c,
        305, height - 200,
        250, 80,
        "SHIPPER",
        ["{{shipper_line_1}}", "{{shipper_line_2}}", "{{shipper_line_3}}"]
    )

    # Container Details
    draw_boxed_section(
        c,
        40, height - 295,
        515, 65,
        "CONTAINER DETAILS",
        [
            "Container No: {{container_no}} - {{container_size}}",
            "Weight: {{weight}} KG",
            "Volume: {{volume}} CBM",
            "Units: {{units}} CTN"
        ]
    )

    # Charges
    draw_boxed_section(
        c,
        40, height - 380,
        515, 75,
        "CHARGES",
        [
            "Freight: USD {{freight_usd}}",
            "CGST @ 2.5%: INR {{cgst}}",
            "SGST @ 2.5%: INR {{sgst}}",
            "Total: USD {{total_usd}} | ROE: {{roe}}"
        ]
    )

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(40, 40, "Generated by {{company_name}} Logistics System")
    c.setFillColor(colors.black)

    c.save()
    print(f"✅ Template PDF generated: {filename}")
